prune

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -50,6 +50,27 @@ jobs:
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./frontend
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
+      - name: Check and prune disk space on EC2
+        env:
+          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
+          AWS_HOST: ${{ secrets.AWS_HOST }}
+          AWS_USER: ${{ secrets.AWS_USER }}
+        run: |
+          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
+          ssh -o StrictHostKeyChecking=no -i private_key ${AWS_USER}@${AWS_HOST} '
+            AVAILABLE_SPACE=$(df --output=avail / | tail -n1)
+            MIN_REQUIRED_SPACE=2097152 # 2GB in KB
+            if [ "$AVAILABLE_SPACE" -lt "$MIN_REQUIRED_SPACE" ]; then
+              echo "Not enough disk space. Pruning Docker resources..."
+              docker system prune -f -a
+              AVAILABLE_SPACE_AFTER_PRUNE=$(df --output=avail / | tail -n1)
+              if [ "$AVAILABLE_SPACE_AFTER_PRUNE" -lt "$MIN_REQUIRED_SPACE" ]; then
+                echo "Error: Still not enough disk space after pruning. At least 2GB is required."
+                exit 1
+              fi
+            fi
+          '
+
       - name: Copy docker-compose.yml and nginx configurations to EC2
         env:
           PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
